### ISSUE TITLE
No held-out test in Kinetics-600

### ISSUE THREAD

**Issue by frankrao** [cvdfoundation/kinetics-dataset#10]
![image](https://user-images.githubusercontent.com/5468443/130942566-81179cd1-64fc-4b13-a344-752966fc8d45.png)

I have downloaded all the videos in https://s3.amazonaws.com/kinetics/600/test/k600_test_path.txt, but found the "held-out test set" missing. There are 72,924 videos in https://s3.amazonaws.com/kinetics/600/annotations/test.csv, but only 59,608 downloaded.

Could you help us how to get the held-out test set in Kinetics-600? Thanks!  @kinetics-cvdf

**Comment by kinetics-cvdf** [comment]
We have added the list of links for the held-out test set.
