### ISSUE TITLE
label missing in k400 test set annotation

### ISSUE THREAD

**Issue by AcherStyx** [cvdfoundation/kinetics-dataset#12]
The original test set download from https://deepmind.com/research/open-source/kinetics contain labels for each video, which is missing in this release.

from deepmind:
```
label,youtube_id,time_start,time_end,split
drinking beer,--6bJUbfpnQ,17,27,test
climbing tree,--8YXc8iCt8,2,12,test
surfing water,--coBvtS-eQ,57,67,test
stomping grapes,--q6ElFyVq0,148,158,test
...
```

download from AWS (the label is missing):
```
youtube_id,time_start,time_end,split
--6bJUbfpnQ,17,27,test
--8YXc8iCt8,2,12,test
--coBvtS-eQ,57,67,test
--q6ElFyVq0,148,158,test
...
```

**Comment by kinetics-cvdf** [comment]
Thanks, replaced the file now. Note that the new one may contain labels for a few more videos than those available to download.
