### ISSUE TITLE
what does is_cc mean?

### ISSUE THREAD

**Issue by shinianzhihou** [cvdfoundation/kinetics-dataset#2]
in k400_train,
the header is:
```bash
label,youtube_id,time_start,time_end,split,is_cc
```
so, what does the is_cc mean?

thanks~

**Comment by kinetics-cvdf** [comment]
Whether the video has a creative commons license.

**Comment by rederoth** [comment]
does anyone know which CC license these videos have (on the spectrum between public domain and all rights reserved) and what license the other videos (is_cc=0) are under? We would like to use a subset of the videos and host them (open access) without getting into trouble
