### ISSUE TITLE
k700_2020_downloader.sh

### ISSUE THREAD

**Issue by sawyermade** [cvdfoundation/kinetics-dataset#24]
This file is all kinds of wrong. First off, uses sudo for everything and then also downloads all the files twice. I will fix it and do a pull request. This is really, really bad.

**Comment by kinetics-cvdf** [comment]
Thank you, shame on me but don't have much time or skill to verify these things. Looking forward to your contribution.

**Comment by TengdaHan** [comment]
@sawyermade Thank you for fixing it. Your contribution will be greatly appreciated!

**Comment by sawyermade** [comment]
No problem. I will be doing a pull request by the end of the day. Already have the downloader fixed, with resume and everything. Going to create a separate script for extracting (shouldn't do all in one) and keep your current naming convention. I will also update the readme as well with instructions on how to complete k700-2020 video download and extraction.

Also, would you like me to write a frame extract script as well? In order to extract the frames from all the downloaded videos.

Really nice aws repo though, much better than the youtube-dl methods due to deleted videos and such.

**Comment by sawyermade** [comment]
Okay cool, I will just do the pull request for download and extraction. I'll still write the script for frame extraction and push it to my forked repo then send you a link to it so you can check it out, if you guys approve, I'll make a pull request for that too.

**Comment by sawyermade** [comment]
Created the pull request. Everything seems to work well!
