### ISSUE TITLE
When decoding some of the kinetics400 videos, "moov atom not found" raised

### ISSUE THREAD

**Issue by irvingzhang0512** [cvdfoundation/kinetics-dataset#3]
Hi, Thanks for your dataset! It's very helpful!

I have successfully download kinetics400 dataset and annotations and have two questions.

1. Some of the videos in kinetics400 train set are corrupted.  Try to decode video with `cv2.VideoCapture("/path/to/video")`, "moov atom not found" raised. The corrupted video file list is here
[test.txt](https://github.com/cvdfoundation/kinetics-dataset/files/6582577/test.txt)

2. There are 240k videos in kinetics400 train set. However, it seems that not all of them(about 238k-239k) are in kinetics400 [train annotations](https://s3.amazonaws.com/kinetics/400/annotations/train.csv)

**Comment by kinetics-cvdf** [comment]
Hi Irving, thanks for your message. We will try to replace these corrupted videos in the training set.
Regarding your second point, some of the videos in the training set were not publicly available anymore from youtube at download time, so they are not included.

**Comment by irvingzhang0512** [comment]
> Regarding your second point, some of the videos in the training set were not publicly available anymore from youtube at download time, so they are not included.

Sorry for my poor english. 

There are 246k samples in training annotation file, 240k video files in tar. However, There are 1-2k video files are not included in training annotation. I may double check this and generate a filelist

**Comment by kinetics-cvdf** [comment]
Added a tar file containing around 1300+ replacement videos (around just 80 missing now, which may be hard to get, so closing this).
