### ISSUE TITLE
使用mmaction2的RGB帧提取工具出现错误

### ISSUE THREAD

**Issue by LEM0NTE** [cvdfoundation/kinetics-dataset#32]
不知道是否有人使用mmaction2的RGB帧提取工具。我下载了k400数据集后，成功解压并按照mmaction2的命名习惯重新命名了文件夹，然后提取RGB帧时却提示没有找到相应的视频文件。
![image](https://user-images.githubusercontent.com/74885294/163969685-9f8477b7-4873-4df1-9a98-62583a23aa39.png)
是否有人可以给我提供一些帮助或者指出可能存在的问题（已经检查过视频文件夹，确定目标路径下有相应的.mp4视频文件）

**Comment by LEM0NTE** [comment]
> 您好，我用ffmpeg首先检查了train文件夹下的视频，确实给出了errorlog，例如如图所示
![image](https://user-images.githubusercontent.com/74885294/164350166-7f24dddd-5ca5-4187-a282-ceecabc63a80.png)
请问这种情况进一步应该怎样处理呢。
感谢您的答复！

**Comment by TengdaHan** [comment]
看起来可能有少量视频文件损坏了。短期办法：忽略这些损坏的视频，照常使用K400，少量视频缺失不影响结果。长期办法：管理员会检查一下AWS里的这些文件，但需要一段时间。

------
(Translate just in case)
Short-term solution: keep using K400, ignoring these corrupted videos. Missing small number of videos have negligible effect on results.
Long-term solution: we could check these videos in AWS, but it takes a while.

To @kinetics-cvdf : It seems some K400 videos are corrupted, right? Are they reported elsewhere?

**Comment by kinetics-cvdf** [comment]
Right, seems like. Probably best is to simply remove them (unless someone has the original uncorrupted versions). Note that this repository will still have a lot more videos than if downloading from youtube.

**Comment by LEM0NTE** [comment]
> 看起来可能有少量视频文件损坏了。短期办法：忽略这些损坏的视频，照常使用K400，少量视频缺失不影响结果。长期办法：管理员会检查一下AWS里的这些文件，但需要一段时间。
> 
> (Translate just in case) Short-term solution: keep using K400, ignoring these corrupted videos. Missing small number of videos have negligible effect on results. Long-term solution: we could check these videos in AWS, but it takes a while.
> 
> To @kinetics-cvdf : It seems some K400 videos are corrupted, right? Are they reported elsewhere?

所以这样看来应该是mmaction那边的问题了，毕竟仍然有一部分视频是正常的，但是他们的工具提取到的帧是0个。感谢您的回复，我去那边的库提issue

**Comment by kinetics-cvdf** [comment]
Thank you Tengda. Will do so.
