### ISSUE TITLE
k600_extract script

### ISSUE THREAD

**Issue by fwtan** [cvdfoundation/kinetics-dataset#36]
`find $curr_dl -type f | while read file; do mv "$file" `echo $file | tr ' ' '_'` done `
should be 
`find $curr_dl -type f | while read file; do mv "$file" `echo $file | tr ' ' '_'`; done`
Missing the semicolon leads to an error.

**Comment by kinetics-cvdf** [comment]
hi, i think this was fixed two days ago, could you check ?
Thanks.
