### ISSUE TITLE
High resolution of videos, is it necessary ?

### ISSUE THREAD

**Issue by georgecloudservices** [cvdfoundation/kinetics-dataset#8]
I would like to ask you about the resolution of the videos in dataset. I download some tar.gz files to inspect the resolutions of videos and I noticed that some videos are in 720p resolution. I think that this is completely unnecessary.  What I mean is, that in most models I know the first action that perform in a dataset is to resize it for example to 227x227, so a resolution of 720p is a waste of space. So:
- Is there a reason that you have such high resolutions in dataset ? 
- Have you tried to run a model with videos with initial high resolution and initial low resolution and notice any difference ?
 
 
In a same situation for Sports1M dataset from youtube, the authors suggest to store the low resolution videos.

**Comment by kinetics-cvdf** [comment]
High-resolution may not be very important for current action recognition results. 
However, Kinetics is used in a variety of applications where resolution may be more helpful, such as space-time localization (e.g. ava-kinetics), video segmentation, optical flow, generative modelling. By keeping original resolutions as much as possible, there are more research possibilities.
